UniversityManagementSystemWebApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.ViewModel;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class CourseController : Controller
    {
        private CourseManager courseManager;
        private DepartmentManager departmentManager;

        public CourseController()
        {
            courseManager = new CourseManager();
            departmentManager = new DepartmentManager();
        }
        //
        // GET: /Course/
        [HttpGet]
        public ActionResult SaveCourse()
        {
            ViewBag.Semester = courseManager.GetAllSemesterForDropdown();
            ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Semester = courseManager.GetAllSemesterForDropdown();
                ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
                string message = courseManager.SaveCourse(course);
                ViewBag.Message = message;
                return View();

            }
            else
            {
                ViewBag.Semester = courseManager.GetAllSemesterForDropdown();
                ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
                string message = "Validation Error";
                ViewBag.Message = message;
                return View();
            }
        }
        [HttpGet]
        public ActionResult CourseStatics()
        {
            ViewBag.Departments = departmentManager.GetAllDepartmentForDropdown();
            return View();
        }


        public JsonResult GetAllCourseListByDeptId(int DepartmentId)
        {
            List<CourseStaticsViewModel> courseStatics = courseManager.GetAllCourseListByDeptId(DepartmentId);
            return Json(courseStatics, JsonRequestBehavior.AllowGet);
        }
    }
}

UniversityManagementSystemWebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.ViewModel;

namespace UniversityManagementSystemWebApp.Controllers
{

    public class StudentController : Controller
    {
        private DepartmentManager aDepartmentManager;
        private StudentManager aStudentManager;
        private CourseManager aCourseManager;
        private EnrollCourseManager aEnrollCourseManager;
        //
        // GET: /Student/

        public StudentController()
        {
            aDepartmentManager = new DepartmentManager();
            aStudentManager = new StudentManager();
            aEnrollCourseManager = new EnrollCourseManager();
            aCourseManager = new CourseManager();
        }
        [HttpGet]
        public ActionResult Register()
        {
            ViewBag.Departments = aDepartmentManager.GetAllDepartments();
            //  ViewBag.Students = aStudentManager.GetAllStudents();
            return View();
        }
        [HttpPost]
        public ActionResult Register(Student student)
        {
            student.RegistrationNo = GenerateRegNo(student);
            ViewBag.Message = aStudentManager.Save(student);
            ViewBag.Departments = aDepartmentManager.GetAllDepartments();

            string deptCode = aDepartmentManager.GetDepartmentbyId(student.DepartmentId).Code;
            string deptName = aDepartmentManager.GetDepartmentbyId(student.DepartmentId).Name;
            StudentDetailsViewModel studentDetails = new StudentDetailsViewModel();
            studentDetails.StudentName = student.StudentName;
            studentDetails.StudentEmail = student.Email;
            studentDetails.StudentRegNo = student.RegistrationNo;
            studentDetails.StudntContactNo = student.ContactNo;
            studentDetails.StudentAddress = student.Address;
            studentDetails.StudentDeptCode = deptCode;
            studentDetails.StudentDeptName = deptName;
            studentDetails.StudentDate = student.Date;

            ViewBag.StudentDetails = studentDetails;

            // ViewBag.StudentDetails = aStudentManager.GetStudentbyDetailsById(student.DepartmentId, student.StudentId);
            // Session["StudentDetails"] = ViewBag.StudentDetails;


            return View();
        }
        [HttpGet]
        public ActionResult Result()
        {
            ViewBag.RegNoList = aEnrollCourseManager.GetAllStudentRegNo();
            return View();
        }

        [HttpPost]
        public ActionResult Result(Student student)
        {
            ViewBag.RegNoList = aEnrollCourseManager.GetAllStudentRegNo();
            return View();
        }

        private string GenerateRegNo(Student student)
        {
            string Year = GetYearFromDate(student.Date);
            string Department = aDepartmentManager.GetDepartmentbyId(student.DepartmentId).Code;
            string Serial = GetSerialFromRowCount(aStudentManager.GetRowCount(student.DepartmentId, Convert.ToInt32(GetYearFromDate(student.Date))));

            return Department + "-" + Year + "-" + Serial;
        }


        public JsonResult GetStudentResultById(int studentId)
        {
            List<ShowResultViewModel> resultList = aStudentManager.GetStudentResultById(studentId);
            return Json(resultList, JsonRequestBehavior.AllowGet);
        }

        private string GetSerialFromRowCount(int rowCount)
        {
            rowCount++;
            string Serial = rowCount.ToString("D3");
            return Serial;
        }

        private string GetYearFromDate(string datefromdatepicker)
        {
            DateTime date = DateTime.ParseExact(datefromdatepicker, "dd/MM/yyyy", null);
            string year = date.Year.ToString();
            return year;
        }


    }
}

UniversityManagementSystemWebApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class TeacherController : Controller
    {

        private TeacherManager teacherManager;
        private DepartmentManager departmentManager;

        public TeacherController()
        {
            teacherManager = new TeacherManager();
            departmentManager = new DepartmentManager();
        }
        //
        // GET: /Teacher/
        [HttpGet]
        public ActionResult SaveTeacher()
        {
            ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
            ViewBag.Designations = teacherManager.GetAllDesignationForDropdown();
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
                ViewBag.Designations = teacherManager.GetAllDesignationForDropdown();
                string message = teacherManager.SaveTeacher(teacher);
                ViewBag.Message = message;
                return View();
            }
            else
            {
                ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
                ViewBag.Designations = teacherManager.GetAllDesignationForDropdown();
                ViewBag.Message = "Validation Error";
                return View();
            }

        }
        [HttpGet]
        public ActionResult AssignCourse()
        {
            ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
            return View();
        }

        [HttpPost]
        public ActionResult AssignCourse(AssignCourse assignCourse)
        {

            ViewBag.Department = departmentManager.GetAllDepartmentForDropdown();
            ViewBag.Message = teacherManager.AssignCourseToTeacher(assignCourse);
            return View();
        }

        public JsonResult GetTeacherByDeptId(int DepartmentId)
        {
            List<Teacher> teacherList = teacherManager.GetAllTeacherByDeptID(DepartmentId);
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllCourseCodeByDeptId(int DepartmentId)
        {
            List<Course> courseCodeList = teacherManager.GetAllCourseCodeByDeptId(DepartmentId);
            return Json(courseCodeList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeacherInfoByTeacherId(int TeacherId)
        {
            Teacher teacherCreditViewModel = teacherManager.GetTeacherInfoByTeacherId(TeacherId);
            return Json(teacherCreditViewModel, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseNameCreditByCourseId(int CourseId)
        {
            Course courseNameCredit = teacherManager.GetCourseNameCreditByCourseId(CourseId);
            return Json(courseNameCredit, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCreditTakenSumOfTeacherByTeacherId(int TeacherId)
        {
            double sumOfCredit = teacherManager.GetCreditTakenSumOfTeacherByTeacherId(TeacherId);
            return Json(sumOfCredit, JsonRequestBehavior.AllowGet);
        }

    }
}

UniversityManagementSystemWebApp/Controllers/indexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class indexController : Controller
    {
        //
        // GET: /index/
        public ActionResult Index()
        {
            return View();
        }
	}
}

UniversityManagementSystemWebApp/Views/Shared/_Layout.cshtml
<<<<<<< HEAD
﻿<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
@*                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
@**@
@*                    Html.ActionLink(*@
@*                    article.Title,*@
@*                    "Item",   $1$actionmethod#1#*@
@*                    "Login" ,$1$controller name.#1#*@
@*                    new { article.articleid },$1$route arguments.#1#*@
@*                    null $1$htmlarguments .. which are none. you need this value otherwise you call the WRONG method ...#1#*@
@*                 *@
@*                    )*@





                    <li>@Html.ActionLink("Register", "Register","Student")</li>
                    <li>@Html.ActionLink("Save Department", "SaveDepartments", "Department")</li>
                    <li>@Html.ActionLink("Enroll Course", "Enroll", "EnrollCourse")</li>
                    <li>@Html.ActionLink("Show Result", "Result", "Student")</li>
                    @*                    <li>@Html.ActionLink("About", "About", "Home")</li>*@
                    @*                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
@*                @Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @RenderSection("scripts", required: false)
   
</body>
</html>
=======
﻿<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
>>>>>>> parent of 9ba993f... Merge branch 'master' into Forman

UniversityManagementSystemWebApp/Views/Shared/_MasterLayout.cshtml
@using System
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"/>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/dist/css/AdminLTE.css" rel="stylesheet" />
    @*    <link href="~/Content/dist/css/skins/skin-black-light.min.css" rel="stylesheet" />*@
    <link href="~/Content/dist/css/skins/skin-green.min.css" rel="stylesheet" />
    @*    <link href="~/Content/dist/css/skins/skin-black.css" rel="stylesheet" />*@
    @*    <link href="~/Content/dist/css/skins/skin-blue.min.css" rel="stylesheet" />*@
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <style>
        .main-login {
            background-color: #fff;
            /* shadows and rounded borders */
            -moz-border-radius: 2px;
            -webkit-border-radius: 2px;
            border-radius: 2px;
            -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        }

        .main-center {
            margin-top: 30px;
            margin: 0 auto;
            max-width: 550px;
            padding: 40px 40px;
        }

        input[readonly].readonly {
            background-color: transparent;
            -webkit-box-shadow: none;
            -ms-box-shadow: none;
            box-shadow: none;
        }

        hr {
         
            border-top: 1px dashed #8c8b8b;
        }
    </style>



    @Scripts.Render("~/bundles/modernizr")
    @*    @Scripts.Render("~/bundles/jquery")*@
</head>
<body class="hold-transition skin-green sidebar-mini sidebar-collapse">

    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
       
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>U</b>MS</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>U</b>MS</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div>
                @Html.ActionLink("University Management System", "Index", "index",null,new{@class = "navbar-brand"})
            </div>
           
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <!-- Tasks Menu -->

                    <!-- User Account Menu -->
                    <!-- Control Sidebar Toggle Button -->

                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users fa"></i> <span> Student</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Regster New Student", "Register", "Student")</li>
                            <li> @Html.ActionLink("Enroll A Student", "Enroll", "EnrollCourse")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user-circle-o"></i> <span> Teacher</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save New Teacher", "SaveTeacher", "Teacher")</li>
                            <li> @Html.ActionLink("Course Assign to Teacher", "AssignCourse", "Teacher")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-building-o"></i> <span> Department</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save New Department", "SaveDepartments", "Department")</li>
                            <li> @Html.ActionLink("Show Department Details", "DepartmentDetails", "Department")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-book"></i> <span> Course</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save New Course", "SaveCourse", "Course")</li>
                            <li> @Html.ActionLink("Show Course Statics", "CourseStatics", "Course")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-trophy"></i> <span> Result</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save Result", "SaveResult", "StudentResult")</li>
                            <li> @Html.ActionLink("Show Result Statics", "Result", "Student")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-object-group"></i> <span> Class Room</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Allocate Classrooms", "Save", "AllocateClassRoom")</li>
                            <li> @Html.ActionLink("Show Class Schedule", "ViewClassShedule", "AllocateClassRoom")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gears fa"></i> <span> Tasks</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("UnAllocate All Classrooms", "UnAllocatClass", "UnAllocateAllClassRoom")</li>
                            <li> @Html.ActionLink("UnAssign All Courses", "UnAssignCourse", "UnassignAllCourses")</li>
                        </ul>
                    </li>

                  
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <!-- search form (Optional) -->
            <!-- /.search form -->
            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-users fa"></i> <span> Student</span>
                        <span class="pull-right-container">
                            <i class="fa fa-users fa pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("Regster New Student","Register","Student")</li>
                        <li> @Html.ActionLink("Enroll A Student", "Enroll", "EnrollCourse")</li>
                    </ul>
                    
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-user-circle-o"></i> <span> Teacher</span>
                        <span class="pull-right-container">
                            <i class="fa fa-user-circle-o pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("Save New Teacher", "SaveTeacher", "Teacher")</li>
                        <li> @Html.ActionLink("Course Assign to Teacher", "AssignCourse", "Teacher")</li>
                    </ul>

                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-building-o"></i> <span> Department</span>
                        <span class="pull-right-container">
                            <i class="fa fa-building-o pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("Save New Department", "SaveDepartments", "Department")</li>
                        <li> @Html.ActionLink("Show Department Details", "DepartmentDetails", "Department")</li>
                    </ul>

                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-book"></i> <span> Course</span>
                        <span class="pull-right-container">
                            <i class="fa fa-book pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("Save New Course", "SaveCourse", "Course")</li>
                        <li> @Html.ActionLink("Show Course Statics", "CourseStatics", "Course")</li>
                    </ul>

                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-trophy"></i> <span> Result</span>
                        <span class="pull-right-container">
                            <i class="fa fa-trophy pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("Save Result", "SaveResult", "StudentResult")</li>
                        <li> @Html.ActionLink("Show Result Statics", "Result", "Student")</li>
                    </ul>

                </li>


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-object-group"></i> <span> Class Room</span>
                        <span class="pull-right-container">
                            <i class="fa fa-object-group pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("Allocate Classrooms", "Save", "AllocateClassRoom")</li>
                        <li> @Html.ActionLink("Show Class Schedule", "ViewClassShedule", "AllocateClassRoom")</li>
                    </ul>

                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-tasks"></i> <span> Actions</span>
                        <span class="pull-right-container">
                            <i class="fa fa-tasks pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li> @Html.ActionLink("UnAllocate All Classrooms", "UnAllocatClass", "UnAllocateAllClassRoom")</li>
                        <li> @Html.ActionLink("UnAssign All Courses", "UnAssignCourse", "UnassignAllCourses")</li>
                    </ul>

                </li>
                fa fa-tasks
            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>
    <div class="content-wrapper">




        <section class="content container-fluid">
            <!--------------------------
            | Your Page Content Here |
            -------------------------->
            @RenderBody()


        </section>





    </div>
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; @DateTime.Now.Year <a href="#">Team Danpithe</a>.</strong> All rights reserved.
    </footer>
    @*    <footer>*@
    @*        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
    @*    </footer>*@


    @*    @Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/dist/js/adminlte.min.js"></script>

</body>
</html>