UniversityManagementSystemWebApp/Models/AllocateClassRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class AllocateClassRoom
    {
        public int ClassId { get; set; }

        [DisplayName("Department")]
        [Required(ErrorMessage = "Please Select Department Name")]
        public int DeptId { get; set; }

        [DisplayName("Course")]
        [Required(ErrorMessage = "Please Select Course Name")]
        public int CourseId {get;set;}


        [DisplayName("Room No.")]
        [Required(ErrorMessage = "Please Select Room Name")]
        public int  RoomId {get;set;}

        [DisplayName("Day")]
        [Required(ErrorMessage = "Please Select A Day")]
        public int  DayId {get;set;}


        [DisplayName("From")]
        [Required(ErrorMessage = "Please Provide From Time")]
        public string FromTime { get; set; }


        [DisplayName("To")]
        [Required(ErrorMessage = "Please Provide To Time")]
        public string ToTime { get; set; }
        public string Action { get; set; }
    }
}

UniversityManagementSystemWebApp/Models/ViewModel/ViewClassSheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models.ViewModel
{
    public class ViewClassSheduleViewModel
    {
        public int CourseId { get; set; }
        public string CourseCode { get; set; }

        public string CourseName { get; set; }

        public List<string> Scheduleinfo = new List<string>();
    }
}

UniversityManagementSystemWebApp/Controllers/AllocateClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.ViewModel;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class AllocateClassRoomController : Controller
    {
        private AllocateClassRoomManager allocateClassRoomManager;


        public AllocateClassRoomController()
        {
            allocateClassRoomManager = new AllocateClassRoomManager();

        }
       


        [HttpGet]
        public ActionResult Save()
        {

            ViewBag.Departments = allocateClassRoomManager.GetDepartmentsForDropdown();
            ViewBag.Rooms = allocateClassRoomManager.GetRoomForDropdown();
            ViewBag.WeekDays = allocateClassRoomManager.GetWeekDaysForDropdown();
            return View();
        }

        [HttpPost]
        public ActionResult Save(AllocateClassRoom allocateClassRoom)
        {
            if (allocateClassRoom.FromTime.Length == 7)
            {
                allocateClassRoom.FromTime = "0" + allocateClassRoom.FromTime;
            }
            if (allocateClassRoom.ToTime.Length == 7)
            {
                allocateClassRoom.ToTime = "0" + allocateClassRoom.ToTime;
            }
            if (ModelState.IsValid)
            {
                ViewBag.Departments = allocateClassRoomManager.GetDepartmentsForDropdown();
                ViewBag.Rooms = allocateClassRoomManager.GetRoomForDropdown();
                ViewBag.WeekDays = allocateClassRoomManager.GetWeekDaysForDropdown();
                ViewBag.Message = allocateClassRoomManager.saveAllocateClass(allocateClassRoom);
                return View();
            }
            else
            {
                ViewBag.Departments = allocateClassRoomManager.GetDepartmentsForDropdown();
                ViewBag.Rooms = allocateClassRoomManager.GetRoomForDropdown();
                ViewBag.WeekDays = allocateClassRoomManager.GetWeekDaysForDropdown();
                string message = "Validation Error";
                ViewBag.Message = message;
                return View();
            }
           
        }

        public JsonResult GetCourseByDepartmentId(int DeptId)
        {
            List<SelectListItem> courseList = allocateClassRoomManager.GetCourseByDeparmentId(DeptId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ViewClassShedule()
        {
            ViewBag.Departments = allocateClassRoomManager.GetDepartmentsForDropdown();
            return View();
        }

        //[HttpPost]
        //public ActionResult ViewClassShedule(Department aDeptment)
        //{
        //    ViewBag.Departments = allocateClassRoomManager.GetDepartmentsForDropdown();
        //    ViewBag.ShowDetails = allocateClassRoomManager.showClassDetails(aDeptment);
        //    return View();
        //}

        public JsonResult GetViewClassSheduleByDeptId(int DeptId)
        {
            List<ViewClassSheduleViewModel> viewClassShedulelist = allocateClassRoomManager.showClassDetails(DeptId);
            return Json(viewClassShedulelist, JsonRequestBehavior.AllowGet);
        }
    }
}

UniversityManagementSystemWebApp/Views/AllocateClassRoom/Save.cshtml
@using System.Collections.Generic
@model UniversityManagementSystemWebApp.Models.AllocateClassRoom


@{
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
    ViewBag.Title = "Save ClassRoom";
    List<SelectListItem> departments = ViewBag.Departments;
    List<SelectListItem> rooms = ViewBag.Rooms;
    List<SelectListItem> weekDays = ViewBag.WeekDays;
}



@using (Html.BeginForm("Save", "AllocateClassRoom", FormMethod.Post, new { id = "AllocateClassRoomForm", @class = "form-horizontal  main-center" }))
{
    <div class="form-group">
        <h2>Save Classroom</h2>
    </div>
    <hr/>
    
         if (ViewBag.Message != null)
        {
            <div>
                <label class="form-group input-group alert alert-info">@ViewBag.Message</label>
                <br />
            </div>

        }


    <div class="form-group">

        <label for="DeptId" class="cols-sm-2 control-label">Department</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-building-o" aria-hidden="true"></i></span>
            @Html.DropDownListFor(x => x.DeptId, new SelectList(departments, "Value", "Text"),new {@class = "form-control"})
        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.DeptId, null, new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">

        <label for="CourseId" class="cols-sm-2 control-label">Course</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-book" aria-hidden="true"></i></span>
            @Html.DropDownListFor(x => x.CourseId, new SelectList(string.Empty, "Value", "Text"),new {@class="form-control"})
        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.CourseId, null, new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        <label for="RoomId" class="cols-sm-2 control-label">Room No</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-building-o" aria-hidden="true"></i></span>
            @Html.DropDownListFor(x => x.RoomId, new SelectList(rooms, "Value", "Text"), new { @class = "form-control" })
        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.RoomId, null, new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">

        <label for="DayId" class="cols-sm-2 control-label">Day</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
            @Html.DropDownListFor(x => x.DayId, new SelectList(weekDays, "Value", "Text"), new { @class = "form-control" })
        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.DayId, null, new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">

        <label for="FromTime" class="cols-sm-2 control-label">Form Time</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-clock-o fa" aria-hidden="true"></i></span>
            <div class='input-group date' id='datetimepicker3'>
                @Html.TextBoxFor(x => x.FromTime, new { @class = "form-control", placeholder = "Select Form Time" })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>

        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.FromTime, null, new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">

        <label for="ToTime" class="cols-sm-2 control-label">To Time</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-clock-o fa" aria-hidden="true"></i></span>
            <div class='input-group date' id='datetimepicker4'>
                @Html.TextBoxFor(x => x.ToTime, new { @class = "form-control", placeholder = "Select To Time" })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>

        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.ToTime, null, new { @class = "text-danger" })
        </div>
    </div>

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker3').datetimepicker({
                format: 'LT'
            });
            $('#datetimepicker4').datetimepicker({
                format: 'LT'
            });
        });
    </script>

  
    <div class="form-group control-label">
            <button class="btn btn-success input-group" type="submit">Save</button>
        </div>


}


<script>
    $("#CourseId").append('<option value=""> --Select-- </option>');

    $(document).ready(function () {



        //cascading dropdownlist
        $("#DeptId").change(function () {
            var deptId = $("#DeptId").val();
            // alert("show dept id" + deptId);
            var json = { DeptId: deptId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseByDepartmentId","AllocateClassRoom")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $("#CourseId").empty();
                    $.each(data, function (key, value) {

                        $("#CourseId").append('<option value=' + value.Value + '>' + value.Text + '</option>');
                    });
                }

            });

        });
    });
</script>

UniversityManagementSystemWebApp/Views/AllocateClassRoom/ViewClassShedule.cshtml
@using System.Collections.Generic
@using UniversityManagementSystemWebApp.Models.ViewModel
@model UniversityManagementSystemWebApp.Models.AllocateClassRoom

@{
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
    ViewBag.Title = "View Class Schedule";
    List<SelectListItem> departments = ViewBag.Departments;
    List<ViewClassSheduleViewModel> shedules = ViewBag.ShowDetails;
}



@using (Html.BeginForm("ViewClassShedule", "AllocateClassRoom", FormMethod.Post, new { id = "AllocateClassRoomForm", @class = "form-horizontal  main-center" }))
{

    <div class="form-group">
            <h2>View Class Schedule</h2>
        </div>
        <hr />

    <div class="form-group">
        <label for="DeptId" class="cols-sm-2 control-label">Department</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-building-o" aria-hidden="true"></i></span>
            @Html.DropDownListFor(x => x.DeptId, new SelectList(departments, "Value", "Text"),new {@class = "form-control"})
        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.DeptId, null, new { @class = "text-danger" })
        </div>

    </div>


}
<!--Table for showing details-->
<div class="container">
    <table class="table table-bordered table-hover table-striped">
        <thead class="bg-green-active" id="Tablehead">

        </thead>
        <tbody id="ClassSheduleDetails"></tbody>
    </table>
</div>
<script>

            $(document).ready(function () {



                //cascading dropdownlist
                $("#DeptId").change(function () {
                    var deptId = $("#DeptId").val();

                   var json = { DeptId: deptId };
                    $.ajax({
                        type: "POST",
                        url : '@Url.Action("GetViewClassSheduleByDeptId", "AllocateClassRoom")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {
                            $("#ClassSheduleDetails").empty();
                            $("#Tablehead").empty();
                            $("#Tablehead").append('<tr> <th>CourseCode</th> <th>CourseName</th> <th>Schedule</th></tr>');
                            $.each(data, function (key, value) {

                                var adiv = document.createElement("div");
                                var td1 = document.createElement("td");
                                var td2 = document.createElement("td");
                                var td3 = document.createElement("td");
                                var trTable = document.createElement("tr");
                                $.each(value.Scheduleinfo, function (index, innerValue) {
                                    var para = document.createElement("p");
                                    para.append(innerValue);
                                    td3.append(para);
                                });
                                td1.append(value.CourseCode);
                                td2.append(value.CourseName);
                                trTable.append(td1, td2, td3);
                                $("#ClassSheduleDetails").append(trTable);

                            });
                        }

                    });

                });
            });
</script>