UniversityManagementSystemWebApp/Models/Student.cs
<<<<<<< HEAD
﻿using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        [Required(ErrorMessage = "Please Provide Student Name!")]
        public string StudentName { get; set; }
        [Required(ErrorMessage = "Please Provide Contact Number!")]
        [RegularExpression("([0-9]*)", ErrorMessage = "Contact Number must be a natural number")]
        [StringLength(11,MinimumLength = 11,ErrorMessage = "Contact Number Must Be 11 Digit Long!")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "Please Provide Email Address!")]
        [EmailAddress(ErrorMessage = "Please Provide Correct Email Formate!")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:/dd/MM/yyyy}")]
        public string  Date { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Select a Department!")]
        public int DepartmentId { get; set; }
        public string RegistrationNo { get; set; }


    }
=======
﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }

        public string ContactNo { get; set; }

        public string Email { get; set; }

        public string Date { get; set; }

        public string Address { get; set; }

        public int DepartmentId { get; set; }

        public string RegistrationNo { get; set; }
        
    }
>>>>>>> parent of 9ba993f... Merge branch 'master' into Forman
}

UniversityManagementSystemWebApp/Controllers/EnrollCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.ViewModel;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class EnrollCourseController : Controller
    {

        private CourseManager aCourseManager;
        private EnrollCourseManager aEnrollCourseManager;
        private StudentManager aStudentManager;
        public EnrollCourseController()
        {
            aCourseManager = new CourseManager();
            aEnrollCourseManager = new EnrollCourseManager();
            aStudentManager = new StudentManager();
        }
        //
        // GET: /Enroll/
        //        public ActionResult Index()
        //        {
        //            return View();
        //        }

        [HttpGet]
        public ActionResult Enroll()
        {
            //
            ViewBag.RegNoList = aEnrollCourseManager.GetAllStudentRegNo();
            return View();
        }

        [HttpPost]
        public ActionResult Enroll(Enroll enroll)
        {
            ViewBag.RegNoList = aEnrollCourseManager.GetAllStudentRegNo();
            // enroll.GradeId = 14;
            enroll.Action = "insert";
            ViewBag.Message = aEnrollCourseManager.EnrollCourse(enroll);
            return View();
        }


        public JsonResult GetCourseByStudentId(int studentId)
        {
            List<SelectListItem> courseList = aCourseManager.GetAllCourseByStudentIdForDropDownList(studentId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllInfoByStudentId(int studentId)
        {

            StudenResultViewModel studentinfo = aEnrollCourseManager.GetAllStudentInfoByStudentId(studentId);
            return Json(studentinfo, JsonRequestBehavior.AllowGet);
        }
    }


}

UniversityManagementSystemWebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.ViewModel;

namespace UniversityManagementSystemWebApp.Controllers
{

    public class StudentController : Controller
    {
        private DepartmentManager aDepartmentManager;
        private StudentManager aStudentManager;
        private CourseManager aCourseManager;
        private EnrollCourseManager aEnrollCourseManager;
        //
        // GET: /Student/

        public StudentController()
        {
            aDepartmentManager = new DepartmentManager();
            aStudentManager = new StudentManager();
            aEnrollCourseManager = new EnrollCourseManager();
            aCourseManager = new CourseManager();
        }
        [HttpGet]
        public ActionResult Register()
        {
            ViewBag.Departments = aDepartmentManager.GetAllDepartments();
            //  ViewBag.Students = aStudentManager.GetAllStudents();
            return View();
        }
        [HttpPost]
        public ActionResult Register(Student student)
        {
            student.RegistrationNo = GenerateRegNo(student);
            ViewBag.Message = aStudentManager.Save(student);
            ViewBag.Departments = aDepartmentManager.GetAllDepartments();

            string deptCode = aDepartmentManager.GetDepartmentbyId(student.DepartmentId).Code;
            string deptName = aDepartmentManager.GetDepartmentbyId(student.DepartmentId).Name;
            StudentDetailsViewModel studentDetails = new StudentDetailsViewModel();
            studentDetails.StudentName = student.StudentName;
            studentDetails.StudentEmail = student.Email;
            studentDetails.StudentRegNo = student.RegistrationNo;
            studentDetails.StudntContactNo = student.ContactNo;
            studentDetails.StudentAddress = student.Address;
            studentDetails.StudentDeptCode = deptCode;
            studentDetails.StudentDeptName = deptName;
            studentDetails.StudentDate = student.Date;

            ViewBag.StudentDetails = studentDetails;

            // ViewBag.StudentDetails = aStudentManager.GetStudentbyDetailsById(student.DepartmentId, student.StudentId);
            // Session["StudentDetails"] = ViewBag.StudentDetails;


            return View();
        }
        [HttpGet]
        public ActionResult Result()
        {
            ViewBag.RegNoList = aEnrollCourseManager.GetAllStudentRegNo();
            return View();
        }

        [HttpPost]
        public ActionResult Result(Student student)
        {
            ViewBag.RegNoList = aEnrollCourseManager.GetAllStudentRegNo();
            return View();
        }

        private string GenerateRegNo(Student student)
        {
            string Year = GetYearFromDate(student.Date);
            string Department = aDepartmentManager.GetDepartmentbyId(student.DepartmentId).Code;
            string Serial = GetSerialFromRowCount(aStudentManager.GetRowCount(student.DepartmentId, Convert.ToInt32(GetYearFromDate(student.Date))));

            return Department + "-" + Year + "-" + Serial;
        }


        public JsonResult GetStudentResultById(int studentId)
        {
            List<ShowResultViewModel> resultList = aStudentManager.GetStudentResultById(studentId);
            return Json(resultList, JsonRequestBehavior.AllowGet);
        }

        private string GetSerialFromRowCount(int rowCount)
        {
            rowCount++;
            string Serial = rowCount.ToString("D3");
            return Serial;
        }

        private string GetYearFromDate(string datefromdatepicker)
        {
            DateTime date = DateTime.ParseExact(datefromdatepicker, "dd/MM/yyyy", null);
            string year = date.Year.ToString();
            return year;
        }


    }
}

UniversityManagementSystemWebApp/Views/Student/Register.cshtml
@using System.Collections.Generic
@using UniversityManagementSystemWebApp.Models
@using UniversityManagementSystemWebApp.Models.ViewModel
@model  Student

@{
    //    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Register Student";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";


    List<Department> Departments = ViewBag.Departments;
    var StudentDetails = ViewBag.StudentDetails;


}



<div class="container">


    @using (Html.BeginForm("Register", "Student", FormMethod.Post, new { id = "studentRegistrationform", @class = "form-horizontal  main-center" }))
    {
        <div class="form-group">
            <h2>Register New Student</h2>
        </div>
        <hr/>
        
           if (ViewBag.Message != null)
        {
            <div>
                <label class="form-group input-group alert alert-info">@ViewBag.Message</label>
                <br />
            </div>

        }


        <div class="form-group">

            <label for="StudentName" class="cols-sm-2 control-label">Student Name</label>

            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                @Html.TextBoxFor(x => x.StudentName, new { @class = "form-control", placeholder = "Enter Student Name" })
            </div>
            <div class="input-group">
                @Html.ValidationMessageFor(x => x.StudentName, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <label for="ContactNo" class="cols-sm-2 control-label">Contact No</label>

            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-phone fa" aria-hidden="true"></i></span>
                @Html.TextBoxFor(x => x.ContactNo, new { @class = "form-control", placeholder = "Enter Contact No" })

            </div>
            <div class="input-group">
                @Html.ValidationMessageFor(x => x.ContactNo, null, new { @class = "text-danger" })
            </div>

        </div>


        <div class="form-group">
            <label for="Email" class="cols-sm-2 control-label">Email</label>


            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder = "Enter Email" })

            </div>
            <div class="input-group">
                @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label for="Address" class="cols-sm-2 control-label">Address</label>

            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-address-card" aria-hidden="true"></i></span>
                @Html.TextBoxFor(x => x.Address, new { @class = "form-control", placeholder = "Enter Address" })

            </div>
            <div class="input-group">
                @Html.ValidationMessageFor(x => x.Address, null, new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <label for="Date" class="cols-sm-2 control-label">Date</label>
            @*  <input type='text' class="col-md-10" id='Date' name="Date"/>*@
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                @Html.TextBoxFor(x => x.Date, new { @class = "form-control", placeholder = "Select Date" })

            </div>
            <div class="input-group">
                @Html.ValidationMessageFor(x => x.Date, null, new { @class = "text-danger" })
            </div>

            <script type="text/javascript">
                $(function () {
                    $('#Date').datetimepicker({
                        format: 'DD/MM/YYYY'
                    });
                });
            </script>


        </div>

        <div class="form-group">
            <label for="DepartmentId" class="cols-sm-2 control-label">Department</label>

            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-building-o" aria-hidden="true"></i></span>
                @Html.DropDownListFor(x => x.DepartmentId, new SelectList(Departments, "DeptId", "Code"), "--SELECT--", new { @class = "form-control" })
            </div>
            <div class="input-group">
                @Html.ValidationMessageFor(x => x.DepartmentId, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group control-label">
            <button class="btn btn-success input-group" type="submit">Register</button>
        </div>

     

    }

    @if (ViewBag.Message != null && ViewBag.Message.Equals("Save Successful"))
    {
        <hr />
        <div class="container">
            <table class="table table-bordered table-hover table-striped">
                <thead class="bg-green-active">
                    <tr>
                        <th>Name</th>
                        <th> Registration No</th>
                        <th>Email</th>
                        <th>Contact NO</th>
                        <th>Date</th>
                        <th>Address</th>
                        <th>Department Code</th>
                        <th>Department Name</th>
                    </tr>
                </thead>
                <tbody>

                    <tr>
                        <td>@StudentDetails.StudentName</td>
                        <td>@StudentDetails.StudentRegNo</td>
                        <td>@StudentDetails.StudentEmail</td>
                        <td>@StudentDetails.StudntContactNo</td>
                        <td>@StudentDetails.StudentDate</td>
                        <td>@StudentDetails.StudentAddress</td>
                        <td>@StudentDetails.StudentDeptCode</td>
                        <td>@StudentDetails.StudentDeptName</td>

                    </tr>
                    @*<tr>
                            <td></td>
                        </tr>*@
                </tbody>

            </table>
        </div>

    }
</div>

UniversityManagementSystemWebApp/Views/Student/Result.cshtml
@using System.Collections.Generic
@using UniversityManagementSystemWebApp.Models
@model UniversityManagementSystemWebApp.Models.Student

@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
    List<Student> RegNoList = ViewBag.RegNoList;
}




@using (Html.BeginForm("Register", "Student", FormMethod.Post, new { id = "studentResultform", @class = "form-horizontal  main-center" }))
{
    <div class="form-group">
        <h2>Show Result</h2>
    </div>
    <hr/>
    <div class="form-group">
        <label for="StudentId" class="cols-sm-2 control-label">Student</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user" aria-hidden="true"></i></span>
            @Html.DropDownListFor(x => x.StudentId, new SelectList(RegNoList, "StudentId", "RegistrationNo"), "--SELECT--",new{@class="form-control"})
        </div>
        <div class="input-group">
            @Html.ValidationMessageFor(x => x.StudentId, null, new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <label for="Name" class="cols-sm-2 control-label">Name</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-user" aria-hidden="true"></i></span>
            <input class="readonly form-control" type='text' name="Name" id="Name" readonly="readonly" />

        </div>

    </div>

    <div class="form-group">
        <label for="Email" class="cols-sm-2 control-label">Email</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-envelope" aria-hidden="true"></i></span>
            <input class="readonly form-control" type='text' name="Email" id="Email" readonly="readonly" />

        </div>

    </div>

    <div class="form-group">
        <label for="Department" class="cols-sm-2 control-label">Department</label>

        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-building-o" aria-hidden="true"></i></span>
            <input class="readonly form-control" type='text' name="Department" id="Department" readonly="readonly" />

        </div>

    </div>
    <div class="form-group control-label">
        <button class="btn btn-success input-group" type="submit">Print PDF</button>
    </div>
 

}


<div class="container">
    <table class="table table-bordered table-striped table-hover">
        <thead class="bg-green-active" id="Tablehead">

        </thead>
        <tbody id="ShowResult"></tbody>
    </table>
</div>


<script type="text/javascript">


    $(document).ready(function () {

        $("#StudentId").change(function () {
            var studentId = $("#StudentId").val();
            // alert("show dept id " + studentId);
            var json = { StudentId: studentId };
            //for all Student info name,email,dept
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetAllInfoByStudentId", "EnrollCourse")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    if (data != null) {
                        $('#Name').val(data.StudentName);
                        $('#Email').val(data.Email);
                        $('#Department').val(data.DeptCode);
                    } else {
                        alert("Something went wrong");
                    }
                }

            });




            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStudentResultById", "Student")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $("#Tablehead").empty();
                    $("#ShowResult").empty();
                    $("#Tablehead").empty();
                    $("#Tablehead").append('<tr> <th>Course Code</th> <th>Course Name</th> <th>Grade</th></tr>');
                    $.each(data, function (key, value) {

                        $("#ShowResult").append('<tr> <td>' + value.CourseCode + '</td> <td>' + value.CourseName + '</td> <td>' + value.Grade + '</td></tr>');

                    });
                }

            });

        });
    });



</script>